export const SIDEBAR_COOKIE_NAME = 'sidebar_state'
export const SIDEBAR_WIDTH_STORAGE_KEY = 'sidebar_width'
export const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7
export const SIDEBAR_WIDTH = '16rem'
export const SIDEBAR_WIDTH_MOBILE = '18rem'
export const SIDEBAR_WIDTH_ICON = '3rem'
export const SIDEBAR_KEYBOARD_SHORTCUT = '.'
export const SIDEBAR_MIN_WIDTH_PX = 240
export const SIDEBAR_MAX_WIDTH_PX = 384
export const SIDEBAR_DRAG_THRESHOLD_PX = 4
